language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
    allow_failures:
        - php: 5.6
        - php: hhvm

before_script: composer install --prefer-source
before_script: cp app/config/parameters.yml.dist app/config/parameters.yml

after_failure: "cat /home/travis/build/gimler/symfony-rest-edition/app/logs/test.log"

script: phpunit -c app
